### ISSUE TITLE
Review examples

### ISSUE THREAD

**Issue by BTWS2** [dwengovzw/Blockly-for-Dwenguino#111]
- [x] Add comment for `LEDS`, because this variable doesn't exist in Arduino:
- https://github.com/dwengovzw/Blockly-for-Dwenguino/blob/unified/backend/compilation/hardware/dwenguino/avr/libraries/Dwenguino/examples/KnightRider/KnightRider.ino
- https://github.com/dwengovzw/Blockly-for-Dwenguino/blob/unified/backend/compilation/hardware/dwenguino/avr/libraries/Dwenguino/examples/Welcome/Welcome.ino
- https://github.com/dwengovzw/Blockly-for-Dwenguino/blob/unified/backend/compilation/hardware/dwenguino/avr/libraries/Dwenguino/examples/SensorsPlus/SensorsPlus.ino

- [x] Typo in Bluetooth example and indentation
- [x] Add `Blink` example
- [x] Add needed components
- [x] Describe circuit
- [x] Describe what the example does
- [x] Explain each step

**Comment by tomneutens** [comment]
We are not planning on supporting Arduino boards. It is also impossible to transfer the downloaded binaries to an Arduino since we have a custom bootloader on the Dwenguino. The focus is the Dwenguino platform and we do not want to confuse users with extra comments regarding the Arduino platform.

The current examples are copied from the ones we had in the Arduino ide plugin. In the long term, we want to add code snippets for specific tasks which could be opened in a new tab.

**Comment by tomneutens** [comment]
If you want to add extra comments to explain what the code does, you can add them to this [file](https://github.com/dwengovzw/Blockly-for-Dwenguino/blob/develop/Blockly-for-Dwenguino/DwenguinoIDE/js/src/textual_editor/dwenguino_code_samples.js)

You can do this directly on github.
